### ISSUE TITLE
Hack Request List

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#1]
At a later date, I'll move this to the README so that people can simply submit PRs to update.
- PLATS + [DEM data](http://ned.usgs.gov/) in Minecraft a la [Code for Vermont's](https://github.com/codeforbtv) NDoCH project [LakeCraft](http://vtrural.org/programs/digital-economy/updates/lakecraft).
- PLATS + [The Census API](https://www.census.gov/developers/) to calculate the % of a city's population that lives within walking distance of a park or trail, a la the Trust for Public Land / [GreenInfo](https://github.com/greeninfo) Network's [ParkScore](http://parkscore.tpl.org/) project.
- PLATS imported into OSM ([Guidelines](http://wiki.openstreetmap.org/wiki/Import/Guidelines))
- Redeploy [Adopt-a-Hydrant](https://github.com/codeforamerica/adopt-a-hydrant) as Adopt-a-Trail using PLATS data.

**Comment by junosuarez** [comment]
@alanjosephwilliams was this closed with an update to the readme as mentioned in the issue? I'm interested in continuing to follow this issue.

**Comment by alanjosephwilliams** [comment]
@jden I chose to break out each idea into a separate issue (now finished), rather than the readme. I'm open to feedback on process though.

**Comment by junosuarez** [comment]
That's a good strategy! Labels work great for organizing / grouping github issues

For the sake of anyone coming across this, from what I could tell, the resulting broken-out issues are:
- #8 #9 #10 #11 #12

**Comment by anselmbradford** [comment]
Hey guys, I've added the "hack request" label to these issues. This is a convention that is spread across several CfA repos that I picked up from @ondrae. You can advertise one URL to bring them up:
https://github.com/codeforamerica/PLATS/issues?labels=hack+request&state=open

Considering fleshing out details of skills needed and check boxes of steps needed for implementation, if applicable. See these examples:
https://github.com/codeforamerica/ohana-web-search/issues/288
https://github.com/codeforamerica/ohana-web-search/issues/338
https://github.com/codeforamerica/bizfriendly-api/issues/45

**Comment by alanjosephwilliams** [comment]
This is a great improvement, thanks Ans! We will definitely flesh out the
skills need and steps in the coming days.

On Tue, May 13, 2014 at 11:34 PM, Ans notifications@github.com wrote:

> Hey guys, I've added the "hack request" label to these issues. This is a
> convention that is spread across several CfA repos that I picked up from
> @ondrae https://github.com/ondrae. You can advertise one URL to bring
> them up:
> 
> https://github.com/codeforamerica/PLATS/issues?labels=hack+request&state=open
> 
> Considering fleshing out details of skills needed and check boxes of steps
> needed for implementation, if applicable. See these examples:
> codeforamerica/ohana-web-search#288https://github.com/codeforamerica/ohana-web-search/issues/288
> codeforamerica/ohana-web-search#338https://github.com/codeforamerica/ohana-web-search/issues/338
> codeforamerica/bizfriendly-api#45https://github.com/codeforamerica/bizfriendly-api/issues/45
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/PLATS/issues/1#issuecomment-43046930
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by louh** [comment]
Is this Hack Requests repo still being used? https://github.com/codeforamerica/hack-requests

I just sent that link out to someone.

**Comment by alanjosephwilliams** [comment]
Doesn't seem particularly active. No commits or issues for a couple months.

On Wed, May 14, 2014 at 5:13 AM, Lou Huang notifications@github.com wrote:

> Is this Hack Requests repo still being used?
> https://github.com/codeforamerica/hack-requests
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/codeforamerica/PLATS/issues/1#issuecomment-43072622
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by migurski** [comment]
No, not strongly active. It is/was a first draft of ideas for hack requests, a few got some traction and saw some progress on a few. We still use the term though, and @ondrae’s plan for moving to issue labels is the current plan.
