### ISSUE TITLE
what does converter do if there are two columns with acceptable field names for the same column type?

### ISSUE THREAD

**Issue by ryanbranciforte** [codeforamerica/OpenTrails#107]

**Comment by migurski** [comment]
Do you mean, for example, if there is both a “trail” and “trailname” column and it needs to decide which one to use?

The transformer functions all work in order, so for [the name example](https://github.com/codeforamerica/OpenTrails/blob/master/open_trails/transformers.py#L75) it’ll use the first thing it finds when looking at _name_, _trail_, _trailname_, _trail name_, etc. in order.

**Comment by ryanbranciforte** [comment]
that clears it up, thnks @migurski
