### ISSUE TITLE
Project Idea: Trailhead Blitz

### ISSUE THREAD

**Issue by jmoe** [codeforamerica/OpenTrails#16]
Let's figure out a cool way for the community to contribute trailhead data by going out into the field and taking photos! It would be great to come away with something that would let people put photos in and get PLATS trailhead data back out.

**Comment by anselmbradford** [comment]
What's the linking of photos to trails look like in this idea? Is it photos linked to a specific trail manually or linking to [geotagged photos](http://en.wikipedia.org/wiki/Geotagged_photograph) or both?

**Comment by jmoe** [comment]
Not sure yet! :-) But I believe photos would end up being linked to Trailheads, which are linked to Trails. Totally spitballing here but I imagine a workflow like  
1. User takes new photo with mobile device (location is pulled from GPS), or selects existing photo (location is pulled from EXIF data)
2. User reviews and is able to verify or correct location (sort of like how Uber allows user to specify exact pickup location) on a displayed map (that hopefully displays existing PLATS data for area)
3. User confirms location, adds a Name, maybe some other metadata like "kiosk", "water", "bathrooms", etc., maybe some narrative description or comments.
4. Trailhead is created based on location, submitted to some backend for storage and retrieval. Photo is associated to Trailhead and also stored in backend.
5. Based on location app can suggest nearby trails that the Trailhead may be associated to, let's user verify. 

At this point an admin interface could be provided to park agencies to confirm Trailheads and use photos. Trailheads themselves would have photos but also by association Trails would have the the photos from the trailheads but also potentially (outside the scope of this idea) at other points along the way.

Worth noting here is that PLATS itself does not currently support the concept of photos, so this would need to be handled solely by the implementation. 

Hope that helps!

**Comment by anselmbradford** [comment]
Perhaps for a prototype the Flickr API could be used to pull in geotagged photos. Then all the photo management could be handled by Flickr (https://www.flickr.com/services/api/flickr.photos.search.html).

**Comment by jmoe** [comment]
Yup! That's exactly what we did for http://www.transitandtrails.org. There are some issues to be aware of with doing that though, specifically around licensing and terms of service. So just be cognizant if that is the implementation. We are hoping to provide a photo storage option as part of an outdoor platform product we are building called OuterSpatial. It's almost ready for testing, we hope to provide free early access at the event, as an option to be evaluated by developers.

**Comment by mtnbkr1** [comment]
Are you thinking about something similar to Everytrail (http://www.everytrail.com/)?
