### ISSUE TITLE
Unique URL for each organization

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/OpenTrails#18]
#### Description

Each organization that is using the Open Trails service will get its own URL to work on. They will use this url to download their open trails data, and also return to to continue the process if they stop in the middle. 

It'll work like this:
- San Antonio Parks goes to our website.
- They put San Antonio Parks as the org name.
- We create a folder on S3 call San-Antonio-Parks
- In that folder are two more folders, /upload and /opentrails
- Anything they upload at opentrails.sexy/san-antonio-parks/upload will go into that san-antonio-parks/upload folder
- All the transformed geojson files will go into san-antonio-parks/opentrails
- If they return to opentrails.sexy/san-antonio-parks, we can see what files are in those folders to know how far along they are in the process.

**Comment by migurski** [comment]
We’re now doing URLs for _uploads_, not stewards or orgs.
