### ISSUE TITLE
Step 2: Upload and Transform Trail Segments

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#20]
_Note: this is a broad-brushstroke description of this phase of transformation. Please see the step by step issues for how each attribute is identified and transformed_
##### Convert Trail Segments
- Solicit a ZIP file that contains a polyline shapefile named "trailsegments.shp", and associated files
  - Give the user feedback about whether files were successfully uploaded
    - Table of relevant top line metadata
      - Number of rows
      - Confirmed it is a polyline shapefile
      - Show file name
    - Error states / messages
      - Not polyline
      - Does not include .dbf  or .shx supporting file
      - Contains 0 rows of data
- Begin a step-by-step "wizard" process to transform the data. Let the user know that they can stop and return to this process using their unique URL.
  - Does the file have an ID column? (1 of 2 required fields)
    - Look for a column titled "id, Id, ID"
    - Ask the user to confirm the correct column as been identified.
      -  If yes, move on.
      - If no, ask the user to select the correct column OR...
      - confirm that no ID column exists, and create one.
  - Does the file have a steward_id column? (2 of 2 required fields)
    - Look for column with title "steward_id"
    - if yes it exists:
      - Check to see if the value == the "id" field in stewards.csv
      - If valid, success. If not valid, update.
    - If not, create an empty steward_id key and populate it with id from steward.csv
  - Identify Activity Fields (not required, but most will include)
    - Identify each activity (foot, bike, horse, ski, motor_vehicles, wheelchair)
    - Update field names and values to be compliant with OpenTrails
  - Identify columns not included in OpenTrails--and see if they can be included as osm_tags
    - For each extra field, ask the user if they would like to include it or discard it
    - Give a detailed explanation of the osm_tags field and Extension Profiles
    - This section should be revisited once the full conversion flow is established.

**Comment by migurski** [comment]
A variant of this is now done.
