### ISSUE TITLE
Validate names of files uploaded

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#21]
#### Description

Before agency users upload data, we are going to ask them to rename the files to meet those names required by the specification. Specifically:
- trailsegments.shp
- trailheads.shp
- areas.shp

and
- namedtrails.csv
- stewards.csv

Thus, we want to:
- [ ] evaluate the names of the files
- [ ] show the names of the files when uploaded
- [ ] throw an error if they do not meet the expected names
- [ ] give positive feedback if they do

**Comment by migurski** [comment]
In the spirit of Jon Postel, could the script use the geometry type of each file to guess which is which? Linestrings must be segments, Points must be trail heads.

**Comment by alanjosephwilliams** [comment]
Right--we have a single file for each geometry type, so that inference should be straightforward.

We were thinking that we would be very specific in what we ask from input data:
- A single zip file which contains the complete set of files required for each layer of geodata (shp, sbn, dbf, etc.) --though we don't require all 3 layers (trailheads, segments, areas) be present.
- That there not any folders in that zip file (say one folder for each set of files for a geometry)
- That the names of those respective files already be updated to "compliant" names.

When it comes to geodata, we can use geometry to infer which file is which. We don't have that luxury with the CSVs.

**Comment by migurski** [comment]
That would give us a lot of duplicate information, which is actually great because it’s an opportunity for people to confirm their meaning. If a points file is called "segments" then it’s a useful piece of feedback to give uploaders, much more than a generic exception and a 400 error. I'm imagining unit tests with lots of calls to self.assertRaises()…

**Comment by migurski** [comment]
The process now requires each file to be uploaded in turn at a specific point, so this will no longer be asked of users.
