### ISSUE TITLE
Step 3: Upload or Extract Named Trails

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#24]
_Note: this is a broad-brushstroke description of this phase of transformation. Please see the step by step issues for how each attribute is identified and transformed_
#### Description

User is present with two options, and chooses one or the other:
- Upload a spreadsheet or CSV
- Extract them from the previously uploaded trail_segments file.
##### Upload
- Upload a file to be converted
  
  _Basic_
  - Give the user feedback about whether files were successfully uploaded
    - File name and extension
    - Number of rows
  - Error states
    - Incorrect file type
    - No columns with strings
    - 0 rows of data
  
  _Relationship to trail_segments_
  - Ask user to identify which column contains ids for trail_segments (segment_ids)
    - if they identify a column, check to see if any value matches any value of "id" field in trail_segments.geojson
      - If yes, assume that it is correct for the time being. We may want to add more tests later.
    - If no, report to user that no matches were found. Allow them to:
      - Choose a different column of values. 
        - Repeat the process of checking against values in trail_segments.
      - Report that no associations with segments exist in the file
        - Suggest that the user extract named_trails from trail_segments.
##### Extract
- Explain the process. We will review the geographic data the user uploaded (trail_segments).
- Review each column. Ask the user to confirm each column that represents a name
  - "name1" "trail1" "trail_name" "trailName" "trail2" etc.
- Once the user has identified each column that contains trail names, we will go through the segments.
- For each unique string value found across those columns/keys, create a new row in a new file called    named_trails.
- For each segment that has an instance of a unique string value, add its "id" to a a field/array called  "segment_ids" for the row associated with the unique string value.

**Comment by migurski** [comment]
A variant of this is now done.
