### ISSUE TITLE
"id" column identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#26]
### Goal

We need to identify or create a unique id for each feature in the trail segment data uploaded. We need to check column names in the uploaded shapefile, and determine which (if any) contains values that should be used as the "id" property in the newly-produced GeoJSON file named "trail_segments.geojson".
#### Sample Data

In the sample data we have on hand, 3/7 datasets have a recognizable id.

Those include instances of the following:
- OBJECTID
- TRAILID

In one of these cases, the id is based on an identification scheme. In the other case, it is simply an enumeration of objects/features in the file.
##### key strings: id, trailid, objectid

Assumption: any id present in a file will contain the string "id"
#### Creating a new id scheme for segment files that lack one

We should expect many submissions not to have an id, and thus we need to create an "id" for the segment file routinely.

Potential approaches:
- Enumerate the number of trail segments and assign id values sequentially
- We could check to see if there is a field that contains a trail name. Often, multiple segments will be present to describe the alignment of a single named_trail (this will be discussed further in a separate issue). Using the value of the name field as the base of an id string would provide some value to developers working with the data.

**Comment by migurski** [comment]
Assign a GUID, possibilities include UUID and [Brooklyn Integers](http://www.brooklynintegers.com) (I let Mission Integers expire).

**Comment by junosuarez** [comment]
With Mission Integers gone, I don't even know what to make of my life anymore :|

**Comment by migurski** [comment]
It got priced out of the Mission.

**Comment by junosuarez** [comment]
Also, +1 for UUIDs. This enables really cool things like creating (and reliably syncing) new trailheads in an offline environment, such as from a mobile offline-first web application.

**Comment by migurski** [comment]
I’ve [gone with numeric IDs](https://github.com/codeforamerica/PLATS/blob/3d40cbb3ad15924b894d9d98fe125a21b3644644/open_trails/transformers.py#L25) for now; [find_segment_id()](https://github.com/codeforamerica/PLATS/blob/3d40cbb3ad15924b894d9d98fe125a21b3644644/open_trails/transformers.py#L56) adequately implements this column.
