### ISSUE TITLE
"steward_id" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#27]
### Goals & Assumptions

Associate each segment feature with a steward. Make this association using "id" value found in the stewards.csv file. 

The "id" value and the stewards.csv file is created in Step 1 of the process described in #23 . It is created only for the single organization that has initiated the upload and convert process. 

We expect segment features to often have no concept of a steward within them. In this use case, the data is being uploaded by the owner of the data.

In another use case, the data is being uploaded by an aggregator of data---such as a regional body, or a state. In these datasets, the concept of stewards is present in the data. The association is typically made via the _steward name_, rather than an ID.
#### Sample Data

Of the sample data on hand, 0/7 segment files contain a column with values representing a unique id corresponding to a steward. 

However, 3/7 of the files _do associate_ segments with a steward--but instead of working with an id, they make the association with a name. Those field names are:

AGENCYNAME 
Steward 
maint_by 
#### Use Case A: No concept of a steward is present
1. Make sure none of the following strings exist in the column names: steward, maint, agency, org, dept
2. Assign the "id" value present in recently-created stewards.csv to all features
#### Use Case B: Stewards _are_ associated via a "Steward Name"
1. Identify the the column that contains one of the following string: steward, maint, agency, org, dept
2. Create a new entry in stewards.csv for each unique value
3. Ask the user to provide a URL for each new row in stewards.csv so that a new id can be generated using our existing approach.
4. Associate those new ids with each segment based on the value of the "Steward Name" field.
#### Other use cases not yet encountered

There may be other use cases wherein a segment is associated with a steward through an pre-existing "ID". In that case, we would hope that there is also a "steward name" type field with which we could create a new entry in stewards.csv

We have not yet encountered this use case in our survey of sample data.

**Comment by migurski** [comment]
See also #58.

**Comment by migurski** [comment]
Generating a single steward with ID `"0"` in a1ce91d98d69dd7ddb95e550fe3ad3050365a2f4.
