### ISSUE TITLE
"motor_vehicles" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#33]
### Goal

Identify whether or not there is an existing column that specifies any use of motor vehicles as an appropriate use. In [OpenTrails](https://github.com/codeforamerica/health-project-ideas/issues?direction=desc&sort=comments&state=open) parlance, we refer to that field as "foot" (derived from OSM). 

The appropriate value is a boolean "yes" or "no"
#### Sample Data Use Case A: One of many fields describing a motorized use exists

In the majority of sample data we have on hand, there is no column that maps directly to "motorized vehicles".

However, a minority of data does have discrete columns specifying the appropriateness of specific types of motorized vehcle—i.e. motorbikes, snowmobiles, etc.

Key strings for that column name include: "MOTORBIKE", "ALLTERVEH", "ATV", "FOURWD", "4WD", "Motorcycle", "Snowmobile"
1. Identify whether or not a column with key strings exists.
2. Assign "yes" or "no" value to "motor_vehicles" attribute based on range of aforementioned boolean values found in sample data. **if any of those aforementioned columns have a positive/true value, then the value of motor_vehciles should be yes.
#### Sample Data Use Case B: A "Combined" Use Field Exists

We have not actually encountered this yet. I doubt that we will find any data that includes motor vehicles in a "combined" or "general" field. I include the use case section here simply to be deliberate about its omission.
#### Sample Data Use Case C: No Use Data Exists

Among the sample data, two agency shapefiles contain no data about appropriate use of trails. In OpenTrails, "use" attributes are not required to exist or have a value.
1. Identify that no column dealing with the types of motorized vehicles use described herein exists.
2. Make it clear to the user that we will create an attribute in their OpenTrails output, as it is recommended.
3. Leave that value null.

**Comment by migurski** [comment]
Implemented in [find_segment_motor_vehicles_use()](https://github.com/codeforamerica/PLATS/blob/3d40cbb3ad15924b894d9d98fe125a21b3644644/open_trails/transformers.py#L244).
