### ISSUE TITLE
Create named_trails.csv, extract Named Trails from segments file

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#35]
### Goal

Create a named_trails.csv file, and populate it based on the values found in "trail name" columns of the segment file.

This goal reflects the fact that few agencies maintain a "named_trails" file discretely from their segments. Most often, many segments in a file will simply have the same value for a column like "TRAIL" or "TRAILNAME"
- Create a named_trails.csv with the following columns
  - name
  - segmentids
  - id
  - description
  - part_of
#### Approach
- Create rows in named_trails.csv 

Each row in named_trails.csv should reflect a unique value found in the segments file column that contains trail names.

Key strings for identifying the trail name column: "trail" "Trail" "name" "TRAILNAME" "trail_name"

In the Ohio data, segments belong to many trails. To describe this, the agencies have included many "trail" columns--"trail1, "trail2", "trail3" and so on.

We should check all columns that contain the key strings, and ask the user to confirm whether or not the contain named trial names.
- Populate the "segment_ids" column with the "id" of each segment that has the unique trail name as a value in its own "TRAIL NAME" or "trail" column.

Lots of segments will have the same "trail name". We want to take the "id" for each fo those segments, and put them into a semi-colon delimited, string-encoded array.
- If the segment file also contains a "System" column, we want that value to populate the "part_of" column found in named_trails.csv

Lots of trail segments belong to both a trail, and a broader or regional trail. In the sample data we have on hand, many times there is a "system" column for describing this relationship.

Key strings for "part_of": "system" "SYSTEMNAME" "Regional" 
- Create the "description column", but do not populate it.

Given the approach we are taking, we do not expect to receive data with narrative descriptions of trails already available in the segments file.

**Comment by migurski** [comment]
Generating a CSV based on same-named trails from segments file in [make_name_trails()](https://github.com/codeforamerica/PLATS/blob/ef7c887ebbc030d80c9acf073155d64b30d42e0c/open_trails/functions.py#L96).
