### ISSUE TITLE
Trailhead "name" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#36]
### Goal

Identify which column in the uploaded point file contains a written name for each trailhead. Assign the values from the column to the "name" attribute defined in OpenTrails.
#### Approach

key strings: "name" "thname"
- Identify whether a name column exists based on the key strings above. 
- If so, use that value as the value of the "name" property for each feature
- If no, leave the "property" null.

**Comment by migurski** [comment]
Added in 78022355.
