### ISSUE TITLE
trailhead  "steward_id" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#38]
### Goal

Associate each trailhead feature with a single steward, so that visitors/end-users know who to contact when assistance or more information is necessary when they are on site.
#### Approach

key string: "steward" "agency" "org" "maint" 

**Use Case A: No steward information in the trailhead file**

We have not yet seen sample data for trailhead in which a steward is identified either by name (as we saw for segments per #27) or by id.

Thus, we should expect to create a steward_id property and populate the value for each feature with the "id" of the steward organization conducting the upload and transformation process.

**Use Case B: Steward identified by name**

Though we have not yet seen this in sample data, we should expect some aggregators of trail system data to provide trailhead features maintained by multiple stewards. We see this with segments. In those instances, stewards were identified by name. Our approach was to create a new entry in stewards.csv for each unique value present. 

We should check to see if any column contains the aforementioned key strings. If they do, we should see if the string values contained therein match to any of the "name" values in stewards.csv. If they do match, we should grab the "id" from that row in stewards.csv, and assign it as the value of "steward_id" for that trailhead feature.

**Comment by migurski** [comment]
Handled in 78022355 and 3f41db78.
