### ISSUE TITLE
trailheads "trail_ids" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#39]
### Goal

The primary value of trailheads comes from their role as points of access for named trails. 
We want to associate each trailhead feature with one or more feature in named_trails.csv through the "id" of those named_trails.

key strings: "trail" trailname" trail#"
#### Approach

Use Case A: One or more trail name columns exist

In the Ohio data, the trailhead data includes associations with multiple named trails through the same approach found in segments--the existence of multiple "trail#" columns containing the "name" value of trails in named_trails.csv.

Use Case B: No association with trails exists

In the sample data we have on hand, there are no associations with trails per se. For the purposes of OpenTrails, this is problematic. 

My recommendation would be that if no associations with trails exist, we should go ahead and produce non-compliant data, but give the user a warning that the data is not compliant, and perhaps flag it as such in the data.

Alternatively, we could:
- Give the user the opportunity to manually identify which named trails can be accessed via each trailhead feature. This might be feasible for small data sets.
- Use spatial analysis to identify which segment is closes to the trailhead, and associate the trailhead with the named_trails that the segment is a constituent part of.

**Comment by alanjosephwilliams** [comment]
The needs here have changed, as OpenTrails v1.0 is being amended.

features in trailheads.geojson will now be associated with trail and trail attributes via relationships with features in  trail_segments.geojson rather than named_trails.csv

### Goal

Associate each trailhead with one or more trail segment via an array of ids. The property name is "segment_ids". The appropriate value is a string-encoded array containing an arbitrary number of strings that match the "id" property for features found in trail_segments.geojson.

### First priority

The converter should look for any field name containing the following keywords:

"trail", "trails", "segments", "segment_id", 

_the converter should look for an arbitrary number of these fields_, then create the string-encoded array from the concatenation of those values.

### Second priority

At least one major OpenTrails publisher (Ohio) associates their trailheads with trails via "trail names". They have seven columns numbered "Trail1" "Trail2"  "Trail3" and so on. The string values in these fields match features in named_trails.csv.

We should grab each of the strings in these columns, iterate through named_trails, and for each match, grab all the "id" of each segment associated with that named_trail--which we will then use to populate "segment_ids"

**Comment by migurski** [comment]
First priority fixed; let's make the second priority into a new ticket if it becomes important.

**Comment by alanjosephwilliams** [comment]
@migurski I have created a separate ticket for "second priority", which can be found now in #84. We had a few agencies do the work to make associations between trailheads and named_trails, and it would be good to serve them, despite the specification's change to create a relationship directly between trailheads and trail_segments.
