### ISSUE TITLE
trailhead "restrooms" identification/creation

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#44]
### Goal

Identify whether or not the uploaded trailhead data contains an indication as to whether drinking water is available on site. 
#### Approach

key strings: "restroom" "bathroom", "toilet"

In the majority of sample data, no column describing the presence of restrooms exists. In this case, leave the value of the parking attribute null.

In a minority of sample data we have on hand, a column specifying whether or not restrooms does exist, and the values provided are booleans.
- determine whether a column name containing one or more key strings exists
- if so, translate the boolean values provided into the OpenTrails-compliant boolean "yes" or "no"
- If not, create the property "restrooms" but leave the value null.

**Comment by migurski** [comment]
Fixed in 76c71462 & 78022355.
