### ISSUE TITLE
Warning / Error / Sucess Message Copywriting

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#48]
This ticket documents all of the error messages needed and completed for a complete version of the converter.
#### Segment Messages
- trail ID (find_segment_id)
  - [x] Warning
    - 'No column found for trail ID, such as "id" or "trailid". A new numeric ID was created.'
  - [x] Error
  - [ ] Success
- name (find_segment_name)
  - [x] Warning
  - [x] Error
    - 'No column found for trail name, such as "name" or "trail".'
  - [ ] Success
- foot (find_segment_foot_use)
  - [x] Warning
    - 'No column found for foot use, such as "hike" or "walk". Leaving "foot" blank.'
  - [x] Error
  - [ ] Success
- bike (find_segment_bicycle_use)
  - [x] Warning
    - 'No column found for bicycle use, such as "bikes" or "road bike". Leaving "bicycle" blank.'
  - [x] Error
  - [ ] Success
- horse (find_segment_horse_use)
  - [x] Warning
    - 'No column found for horse use, such as "horses", "equestrian", etc. Leaving "horse" blank.'
  - [x] Error 
  - [ ] Success
- ski (find_segment_ski_use)
  - [x] Warning
    - 'No column found for ski use, such as "skiing" or "cross country ski". Leaving "ski" blank.'
  - [x] Error
  - [ ] Success
- wheelchair (find_segment_wheelchair_use)
  - [x] Warning
    - No column found for wheelchair accessibility, such as "accessible" or "ADA". Leaving "wheelchair" blank.'
  - [x] Error
  - [ ] Success
- motor_vehicles (find_segment_motor_vehicles_use)
  - [x] Warning 
    - 'No column found for motor vehicle use, such as "motorbike" or "ATV". Leaving "motor_vehicles" blank.'
  - [x] Error
  - [ ] Success

**Comment by migurski** [comment]
I have created a [set of error HTML files](https://github.com/codeforamerica/PLATS/tree/33eb10d035ad87aeaa622aa4271ee30d0059c3f1/open_trails/templates) for you to populate with words. They are controlled in [`transformers.py`’s messages list](https://github.com/codeforamerica/PLATS/blob/33eb10d035ad87aeaa622aa4271ee30d0059c3f1/open_trails/transformers.py#L69) and displayed by [`get_error`](https://github.com/codeforamerica/PLATS/blob/33eb10d035ad87aeaa622aa4271ee30d0059c3f1/open_trails/routes.py#L303).

**Comment by migurski** [comment]
I have added [new error HTML files](https://github.com/codeforamerica/PLATS/tree/b03a971f464409c2feafa4d4e4cc0dc274b73a21/open_trails/templates) for the validation process in https://github.com/codeforamerica/PLATS/commit/b03a971f464409c2feafa4d4e4cc0dc274b73a21.

**Comment by alanjosephwilliams** [comment]
Satisfied by #71

**Comment by migurski** [comment]
Merged.
