### ISSUE TITLE
Transform NRPA/PRORAGIS Data into PLATS

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#5]
#### Description

The National Recreation and Parks Association's recommended data model, dubbed PRORAGIS, is an asset management model that many park agencies use to maintain their data. While by no means an "80% case", PRORAGIS is likely the data model we will find most consistently among our target audience. 

Let's use NRPA as one of---or the first iteration of--- our input formats for our converter. A good example of PRORAGIS data for trailsegments is from Portland:
https://drive.google.com/a/codeforamerica.org/#folders/0B8q02hJyuselS2pQWDVaSE9Tc0k

And here is a Esri .gdb and set of excel files outlining the model:
https://drive.google.com/a/codeforamerica.org/#folders/0B8q02hJyuselOHYwYzRqSlBKbjQ

@migurski this might also help guide test development.

**Comment by migurski** [comment]
@alanjosephwilliams is this structure now accounted-for in the other issues?

**Comment by alanjosephwilliams** [comment]
@migurski yes, the other issues describe NRPA field names in the "key strings", and generally take their structure into consideration.
