### ISSUE TITLE
Converter Flow

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#50]
###### This page should provide the following information:
- [ ] Guidance on what kind of data to upload.
- [ ] A visual indication that we are soliciting trail segments (polyline data).
- [ ] A visual indication that we are not yet soliciting other data (points and polygons).
- [ ] An indication of acceptable file types—specifically shapefiles, vs. geodatabses.
- [ ] Guidance on which files are required to be zipped up as a valid shapefile
###### This page should provide the following actions:
- [x] Upload zipped shapefile
- [ ] Route to validator (if they have geojson, rather than shapefiles)
###### This page should provide the following information:
- [ ] A table of all field names and a sample value for each
###### This page should provide the following actions:
- [ ] An action to initiate the transformation process
- [ ] A visual indication that the transformation is processing (for large files)
###### This page should provide the following information:
- [ ] A general success message that summarizes transformation work
- [ ] Notes / Messages about the transformation of each column (warnings and errors)
- [ ] A description of the next step required, extracting named trails.
###### This page should provide the following actions:
- [ ] A pathway for feedback about how we are evaluating columns (keyword contributions, etc—Olark?)
- [ ] A pathway to review the specification itself
- [ ] Accept the transformation, and move on the extraction of named trails.
###### This page should provide the following information:
- [ ] A way to list all of the Named Trails extracted. 
- [ ] A visual that indicates the relationship that now exists between two files.
- [ ] Information about the next step required.
###### This page should provide the following actions:
- [ ] A form to create a stewards.csv file and an ID associated with each segment
###### This page should provide the following information:
- [ ] Repeated information about the converter's status as underdevelopment.
- [ ] Information on hosting options, publishing strategies, and perhaps the OpenTrails Course
###### This page should provide the following actions:
- [ ] Download ZIP of data.
- [ ] Return to Tools homepage.
##### Validator Home
# 

This issue is a stub currently being edited.

**Comment by migurski** [comment]
This issue is old, big, and affected by the recent merge. @alanjosephwilliams can you update it with current information?

**Comment by alanjosephwilliams** [comment]
Updated, but I am going to go ahead and close, as I think the extent of the flow has been established.
