### ISSUE TITLE
Reformat Convert/Validate choices on front page to side-by-side layout

### ISSUE THREAD

**Issue by migurski** [codeforamerica/OpenTrails#56]
They're parallel choices.

**Comment by alanjosephwilliams** [comment]
Accomplished via 5695c5e0e78212e1240071842d322b77e38d1ca3. Will close when the PR is merged.

**Comment by migurski** [comment]
Fixed in https://github.com/codeforamerica/PLATS/commit/098d39f3d09f99e6e52dc711132c70c76821cf0e.
