### ISSUE TITLE
Pull next action forms higher on page

### ISSUE THREAD

**Issue by migurski** [codeforamerica/OpenTrails#57]
Each step of the conversion flow has the action forms (upload, etc.) quite far down the page. The primary form element should be below the title but above the main descriptive text.

**Comment by alanjosephwilliams** [comment]
Agreed. I've pull all of the actions above the fold, and updated the titles to reinforce that action in 43388432cb5d224ea84f74307b52028a11513396. I'll leave this ticket open until we merge the PR.

**Comment by migurski** [comment]
Fixed in https://github.com/codeforamerica/PLATS/commit/098d39f3d09f99e6e52dc711132c70c76821cf0e.
