### ISSUE TITLE
Generate or accept stewards.csv 

### ISSUE THREAD

**Issue by migurski** [codeforamerica/OpenTrails#58]
- [x] Render forthcoming `datasets-05-stewards.html` template.
- [x] Complete the form on `/named-trails` or make it possible for a user to upload.

**Comment by alanjosephwilliams** [comment]
@migurski if this can be prioritized on your end, I can make sure the copy/layout is solid for that final page. 

Actually, I suppose just adding a function in routes.py that renders the datasets-05-stewards.html template would allow that front-end work to begin.

**Comment by migurski** [comment]
I can do that—on master, okay?

**Comment by alanjosephwilliams** [comment]
absolutely

On Tue, Jul 8, 2014 at 12:15 AM, migurski notifications@github.com wrote:

> I can do that—on master, okay?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/PLATS/issues/58#issuecomment-48242118.

## 

t:  @alanjosephwilli
p: 817 713 6264
