### ISSUE TITLE
Frontend v1

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#6]
- [x] Apply CfA stylesheets
- [x] Single column layout
- [x] Leaflet map that shows geodata uploaded
- [x] Steward "Profile" Section 
  
  > Form data available to the server in order to assign a unique steward ID, and create stewards.csv
  > Steward profile section should produce the unique URL where the process can be revisited.
- [ ] Upload Section: Simple Infographic
- [ ] Upload action and feedback
  
  > Ask the user to upload a zip file containing all three geodata files. Ask them to name those files "trailsegments", "trailheads" and "areas". Once uploaded, give the user an indication of which files were successfully read and converted. Show that geodata on a map.
- [ ] Create namedTrails from trailsegments

**Comment by alanjosephwilliams** [comment]
heads up @ondrae you can see work in progress here:

http://opentrails-frontend.herokuapp.com/

**Comment by ondrae** [comment]
@alanjosephwilliams and check out the new maps from uploads
http://open-trails.herokuapp.com/

**Comment by migurski** [comment]
Closing this out-of-date ticket.
