### ISSUE TITLE
Fix Sentinel Font Loading Error

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#61]
Console message:

Failed to load resource: the server responded with a status of 403 (Forbidden) http://cloud.typography.com/6435252/678502/css/fonts.css

Because the app is not under codeforamerica.org, we do not have permission to load the typography used by the site (no problem with the rest of CfA styles).

We can always download and load manually in the short term, if necessary.

**Comment by migurski** [comment]
I'll eventually put this under a CfA subdomain, so this will be a non-issue.

**Comment by migurski** [comment]
Live now: http://open-trails.codeforamerica.org
