### ISSUE TITLE
Unicode values in feedback messages—just displayed, or being evaluated?

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#64]
When running some near-OpenTrails compliant data through the validator, many fields generated errors based allowed values.

As seen in the screenshot, the error messages display the unicode tag along with the value that has triggered the error message.

@migurski do you know whether these error messages are triggered because we are evaluating the value and running into the unicode tag as well? Or is the capital-Y in "Yes" (and the corollary for "No") triggered the error, and we simply need to display the values without the unicode tag?

![screenshot 2014-07-12 16 37 03](https://cloud.githubusercontent.com/assets/2983464/3561546/36c43606-09ca-11e4-982e-bfdb3ecacc6f.png)

**Comment by migurski** [comment]
I’m guessing it’s a capital-Y thing.

**Comment by alanjosephwilliams** [comment]
Ok, I'll look into preventing the rendering of the unicode tag then.
