### ISSUE TITLE
ogr2ogr error on segment upload for conversion

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#67]
When uploading the [East Bay Regional Park District segment data](https://github.com/codeforamerica/PLATS/blob/adc021bb2b478058df3d9e7d1efc0a6f55441762/test-files/ebrpd-segments.zip) to the converter locally, there is a ogr2ogr failure. Will investigate further, including trying to reproduce on production, but a screenshot is included below for the time being.

![screenshot 2014-07-12 16 13 30](https://cloud.githubusercontent.com/assets/2983464/3561657/176c0112-09cf-11e4-9a2e-337bb58a8b6f.png)

**Comment by alanjosephwilliams** [comment]
@migurski were you able to reproduce this error? I continue to run into it. @ondrae maybe you could try to reproduce as well?

It appears that it might be related to the filename that is being processes. The files included in the zip are named as follows:
- MstrPln_Trls.shp
- MstrPln_Trls.sbn
- MstrPln_Trls.shx
- MstrPln_Trls.dbf
- MstrPln_Trls.prj
- MstrPln_Trls.shp.xml

The error message is reporting the filename as "._MstrPln_Trils.shp"

The error message on production also seems to one that we could try to improve:
![screenshot 2014-07-14 15 39 43](https://cloud.githubusercontent.com/assets/2983464/3571358/68792d12-0b5c-11e4-9ad4-0c396aedd896.png)

**Comment by migurski** [comment]
I was not able to. The dot-named file does look off, though. Unintended passenger from the Mac file system?

**Comment by migurski** [comment]
Fixed earlier in 6822eca.
