### ISSUE TITLE
Copywriting setting upload time expectations

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#69]
Currently, the upload times for datasets around ~1-2 MB are long enough that I end up tabbing over to other tasks on the web (for both the converter and validator). I suppose this is alright, but I would rather not get tired of waiting before I choose to do so—we should let people know up front that it is going to take a minute or two.

**Comment by alanjosephwilliams** [comment]
Is satisfied in #71

**Comment by migurski** [comment]
Merged.
