### ISSUE TITLE
Investigate heavier-than-usual font-weight of Interstate

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#70]
The default font for body text in the CfA style guide is Interstate Regular. While it appears we are using this same font (and the same fallbacks), Interstate is rendering more heavily on the OpenTrails Tools site compared to the Code for America site. 

Overriding adjustments to the font-weight are no help (though they can render it even heavier). This may resolve itself if the tool migrates under the CfA domain. 

Not urgent, but legibility does suffer as a result of this.

**Comment by migurski** [comment]
Going to mark this closed; it's not in-scope for the Trails app since the CSS comes from outside.
