### ISSUE TITLE
Internal Server Error at step 1

### ISSUE THREAD

**Issue by migurski** [codeforamerica/OpenTrails#75]
http://open-trails.codeforamerica.org/datasets/398c4b76-e93f-4291-85c5-e4cd53a6da62

**Comment by jmoe** [comment]
I was able to reproduce this by trying to upload a file named "opentrails (2).zip" 
When I renamed it "ohio_opentrails.zip" it worked fine.

**Comment by migurski** [comment]
This looks connected to local/remote file storage magic that I'm slowly working on removing.
