### ISSUE TITLE
Allow users with no trailhead data to "skip to download"

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#82]
Currently, we only offer users the ability to download a zipfile of OpenTrails data once they have completed both the trailsegment and trailhead shapefile upload-and-transform process. **We should provide a "skip trailheads, let me download my data now" option for users with no trailhead data.**

Moreover, with today's [amendment to OpenTrails v1.0](https://groups.google.com/forum/#!profile/opentrails-discussion/APn2wQdskUVk-2gvc3xC2Ooh13892I1jZHHPtD9GyTtjlzLpDzgyvqxOjy_HK78g9mYcL_VphKGo/opentrails-discussion/fWTYLV3i8D4/va7Zxwfu0BIJ), trailheads are not directly associated with segments via a "segment_ids" proeprty, which contains values found in trail_segments.geojson's "id" property. For those who have uploaded trail_segments to the converter without unique ids, there could be a use for downloading the converter output, associating trailheads, then uploading trailhead for conversion.

**Comment by migurski** [comment]
Perhaps a "skip this step" button, so they'd continue to move through the process? Rather than a download shortcut.

**Comment by alanjosephwilliams** [comment]
That makes sense to me, certainly. I think I can implement this, so I'm assigning to myself.

**Comment by alanjosephwilliams** [comment]
Resolved via:
f49311a
5d44832
8882ffb
695a583

Next time I'll make that kind of update a feature branch.
