### ISSUE TITLE
Error - During the creation of name_trails.csv

### ISSUE THREAD

**Issue by ryanbranciforte** [codeforamerica/OpenTrails#86]
Data I'm testing is located here: Course_1/County/County of Santa Clara CA/Prepped/Final

Attached is a screenshot of error:
![screen shot 2014-08-18 at 3 21 54 pm](https://cloud.githubusercontent.com/assets/2602563/3959223/3aba55ca-2729-11e4-98bc-94e69baf004a.png)

**Comment by migurski** [comment]
Can you paste that URL so I don't need to transcribe from a JPEG?

**Comment by ryanbranciforte** [comment]
http://open-trails.codeforamerica.org/datasets/84b72a72-3866-4b49-ae74-a143209b51b8/name-trails

**Comment by migurski** [comment]
Thanks!

**Comment by ryanbranciforte** [comment]
:) will posted urls in future!

**Comment by migurski** [comment]
Looks like a bad string in the data someplace. Invalid UTF-8, or sneaky visitor from another character set.

**Comment by migurski** [comment]
There was an “ñ” in the file; I’m going to push a fresh version of the code. Re-visit [step 3](http://open-trails.codeforamerica.org/datasets/84b72a72-3866-4b49-ae74-a143209b51b8/transformed-segments) in five minutes to pick up where you left off.

**Comment by ryanbranciforte** [comment]
hmmm, that makes sense. there is a trail in that park with a tilda in name. i'll see if i can track it down and clean it up, but first will retest with same data so we can test the non-ASCII char update

**Comment by migurski** [comment]
It should be good to go now—I'm explicitly encoding to UTF8.

**Comment by ryanbranciforte** [comment]
worked! thanks michal!
