### ISSUE TITLE
validator giving error when testing converter output OT data

### ISSUE THREAD

**Issue by ryanbranciforte** [codeforamerica/OpenTrails#89]
http://open-trails.codeforamerica.org/checks/6c1034e0-86bb-4bd1-bef8-f03b3d9e5841/upload

**Comment by alanjosephwilliams** [comment]
Hrm, looks like there is a TypeError surfacing in the Heroku logs, saying that arguments for a particular method must only be strings. 

did you change the name of the output files by any chance?

**Comment by migurski** [comment]
It ought to be easier for us to triage these errors. The failure is happening in the [shapefile2geojson() function](https://github.com/codeforamerica/OpenTrails/blob/581328c91ee6aa7944b8f134eb8dd3eb011d70c4/open_trails/transformers.py#L14) so at least we know the zip has been uploaded and can inspect it at this point.

**Comment by ryanbranciforte** [comment]
No, did not change name of the OT files. I did change the name of the zip file. The data is loading into OuterSpatial fine and is showing the map embeds. LMK what I can do re this issue.

**Comment by migurski** [comment]
Looked to be more cases of optimistic treatment of Heroku's filesystem.

**Comment by migurski** [comment]
This now looks okay:

http://open-trails.codeforamerica.org/checks/6c1034e0-86bb-4bd1-bef8-f03b3d9e5841/results

**Comment by ryanbranciforte** [comment]
working! thanks a ton.
