### ISSUE TITLE
Project Idea: "OSM for Parks" Primer

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#9]
#### Idea:

The ability to import trail data into OSM is a primary goal that has driven design of the specification. We've found that describing OSM, and its value, to park agencies and staff is often a challenge. A primer specifically for this audience would go a along way.
#### Description:

A graphically-rich print or web design piece that explains:
- The purpose, scale, and uses of OpenStreetMap.
- The problems governments face around licensing, and how they can be worked around.
- Direction to the PLATS conversion tool, which also outputs OSM-ready data.
- Guidance about how to interact with the import community.

**Comment by jmoe** [comment]
+1

I would be a consumer of this.

**Comment by jmoe** [comment]
Especially useful would be a description of the general philosophy behind how data gets into OSM and what it means to be an authoritative source in the context of OSM. So, really once data is "OSM-ready" what happens next? What are the paths that the data can take to eventually being seen on an OSM map.
