### ISSUE TITLE
add "restrooms" as an acceptable field name for trailheads (if not already)

### ISSUE THREAD

**Issue by ryanbranciforte** [codeforamerica/OpenTrails#90]

**Comment by ryanbranciforte** [comment]
just ran some data thru and it looks like 'restrooms' is not acceptable, but we identify it as acceptable in the OT guidebook. please update
![screen shot 2014-10-23 at 5 18 04 pm](https://cloud.githubusercontent.com/assets/2602563/4763539/50df155c-5b13-11e4-9907-5337e52969d3.png)

**Comment by migurski** [comment]
Would go here: https://github.com/codeforamerica/OpenTrails/blob/master/open_trails/transformers.py#L420

**Comment by ryanbranciforte** [comment]
thanks! i'm not versed in updating code, but i'll see if @jmoe or @alanjosephwilliams can help me out!

**Comment by lyzidiamond** [comment]
Fixed with https://github.com/codeforamerica/OpenTrails/commit/c3ed0bfa90ffa890e16f7be4dc700d389c087d9b!

**Comment by migurski** [comment]
:+1: deploying.
