### ISSUE TITLE
Not all segments are being included in segment_ids

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#92]
In this dataset:
https://drive.google.com/a/codeforamerica.org/?tab=mo#folders/0B8q02hJyuselcFJIeVhRN1pHU0U

There are 12 segments with the value "Coal Creek Trail" in the "trailname" field.
(those segments are "trailid": 249, 250, 251, 252, 253, 295, 297, 298, 299, 336, 337, 338).

In the "named_trails.csv" file that is packaged in the Converter's open-trails.zip output, four different "Coal Creek Trail" rows were created.

![converter_bug](https://cloud.githubusercontent.com/assets/2983464/4070370/80a495fe-2e5a-11e4-9d95-587dfb27271b.png)

We are investigated why this might be the case. It looks like the strings are identicial in all12 rows of the shapefile.

**Comment by ryanbranciforte** [comment]
here is the gis attribute table with the selected "Coal Creek Trail" records. 
![county_boulder](https://cloud.githubusercontent.com/assets/2602563/4070403/61999fc8-2e5b-11e4-85ad-699598a7912b.JPG)

**Comment by jmoe** [comment]
functions.py make_name_trails method seems like a prime suspect

**Comment by alanjosephwilliams** [comment]
Pinging @migurski since he hasn't been mentioned on this thread yet. @jmoe and I are going to take a look either tonight or tomorrow, since this is a critical bug.

**Comment by alanjosephwilliams** [comment]
@migurski  I think we've addressed this with #96—updating the make_named_trails function, and adding a set of agency-schema specific tests for good measure.
