### ISSUE TITLE
update copy on the trails shapefile upload page

### ISSUE THREAD

**Issue by ryanbranciforte** [codeforamerica/OpenTrails#97]
See image. Need to update to reflect that segment ids are used to group segments into full trails. 
![screen shot 2014-09-04 at 10 51 51 pm](https://cloud.githubusercontent.com/assets/2602563/4160665/07624930-34c1-11e4-8d50-64c53d985c7d.png)
@alanjosephwilliams

**Comment by alanjosephwilliams** [comment]
Looks like this is actually the page/view that comes after upload, where we ask the user to review the sample attributes of the data they have uploaded.

The copy you've screen-captured is accurate. Segments need to contain the name of the trail they are a part of. Those names are used to group segments into full trails.

Are you suggesting we should specify that Named Trails are groups of segments, referred to by their id? I think that is implicit—but I'm open to argument that it should be _explicit_.

**Comment by ryanbranciforte** [comment]
Makes sense. Thanks for reviewing.
